apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwarferl
  labels:
    app: dwarferl
spec:
  selector:
    matchLabels:
      app: dwarferl
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: dwarferl
      labels:
        app: dwarferl
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - name: dwarferl
          image: "ghcr.io/pscheid92/dwarferl/dwarferl:{{ required "Set valid .Values.imageVersion entry!" .Values.imageVersion }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GIN_MODE
              value: {{ .Values.environment }}
            - name: FORWARDED_PREFIX
              value: {{ .Values.forwardedPrefix }}
            - name: PGHOST
              value: {{ .Values.database.host }}
            - name: PGDATABASE
              value: {{ .Values.database.dbname }}
            - name: PGUSER
              value: {{ .Values.database.user }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: dwarferl-secret
                  key: pgpassword
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  key: session_secret
                  name: dwarferl-secret
            - name: GOOGLE_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  key: google_client_key
                  name: dwarferl-secret
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  key: google_secret
                  name: dwarferl-secret
            - name: GOOGLE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  key: google_callback_url
                  name: dwarferl-secret
          livenessProbe:
            httpGet:
              path: {{ .Values.forwardedPrefix }}health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
