apiVersion: v1
kind: Secret
metadata:
  name: dwarferl-secret
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "dwarferl-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  {{- $pgpassword := (get $secretData "pgpassword") | default (randAlphaNum 50 | b64enc) }}
  pgpassword: {{ $pgpassword | quote }}

  {{- $session_secret := (get $secretData "session_secret") | default (randAlphaNum 64 | b64enc) }}
  session_secret: {{ $session_secret | quote }}

  {{- $google_client_key := (get $secretData "google_client_key") | default (randAlphaNum 50 | b64enc) }}
  google_client_key: {{ $google_client_key | quote }}

  {{- $google_secret := (get $secretData "google_secret") | default (randAlphaNum 50 | b64enc) }}
  google_secret: {{ $google_secret | quote }}

  {{- $google_callback_url := (get $secretData "google_callback_url") | default (randAlphaNum 50 | b64enc) }}
  google_callback_url: {{ $google_callback_url | quote }}
