apiVersion: v1
kind: Secret
metadata:
  name: dwarferl-secret
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "dwarferl-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  {{- $pgpassword := (get $secretData "pgpassword") | default (randAlphaNum 50 | b64enc) }}
  pgpassword: {{ $pgpassword | quote }}

  {{- $session_secret := (get $secretData "session_secret") | default (randAlphaNum 64 | b64enc) }}
  session_secret: {{ $session_secret | quote }}
