apiVersion: v1
kind: Secret
metadata:
  name: dwarferl-secret
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "dwarferl-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  {{- $user := (get $secretData "user") | default ("admin" | b64enc) }}
  user: {{ $user | quote }}

  {{- $secret := (get $secretData "secret") | default ("admin" | b64enc) }}
  secret: {{ $secret | quote }}

  {{- $pgpassword := (get $secretData "pgpassword") | default (randAlphaNum 50 | b64enc) }}
  pgpassword: {{ $pgpassword | quote }}
