// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package database

import (
	"time"
)

type Redirect struct {
	Short     string
	Url       string
	UserID    string
	CreatedAt time.Time
}

type User struct {
	ID               string
	Email            string
	GoogleProviderID string
}
